title: Amazing image identifier
hero_image: images/banner.png
description: Build an application that uses machine vision to do something cool!
version: 4
listed: false
copyedit: false
last_tested: "2020-07-16"
steps:
  - title: Introduction
  - title: Get setup
  - title: Get inspiration
  - title: Choose an application
  - title: Build a desktop application
  - title: Build a command line tool
  - title: Build a web application
  - title: Classify your image
  - title: Do something with the classifaction
  - title: Share
  - title: Reflect

