---
title: Amazing image identifier
hero_image: images/banner.png
description: Build an application that uses machine vision to do something cool!
version: 4
listed: true
copyedit: true
last_tested: '2020-07-16'
steps:
- title: Introduction
- title: Get set up
- title: Get inspiration
  completion:
  - engaged
- title: Choose an application
- title: Build a desktop application
- title: Build a command line tool
  completion:
  - internal
- title: Build a web application
- title: Classify your image
- title: Do something with the classification
- title: Share
  completion:
  - external
- title: Reflect
  knowledge_quiz:
    path: quiz1
    questions: 3
    passing_score: 3
